version: "3.9"

services:
  employee:
    build: ./employee_app
    ports:
      - "8080:8080"
    volumes:
      - ./expenses_system_db.db:/database/expenses_system_db.db

  manager:
    build: ./manager_app
    ports:
      - "9090:9090"
    volumes:
      - ./expenses_system_db.db:/database/expenses_system_db.db